/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.tokio.school.swing.calculadora.frames;

import com.tokio.school.swing.calculadora.utils.OperationsUtils;
import java.math.BigDecimal;
import java.math.MathContext;
import java.util.LinkedList;
import java.util.Queue;
import java.util.Stack;
import javax.swing.JOptionPane;

/**
 *
 * @author andre
 */
public class CalculadoraFrame extends javax.swing.JFrame {

    public static int LIMIT_NUMS = 100;

    enum OPERATION {
        ADD, SUBTRACT, MULITPY, DIVISION, NONE, INIT
    };
    public static BigDecimal result;
    public static Queue<BigDecimal> num;
    public String numStr, salve;
    public static String auxNum = "";
    public static Stack<OPERATION> operaciones = new Stack<>();

    /**
     * Creates new form NewJFrame
     */
    public CalculadoraFrame() {
        initComponents();
        initVars();

        setLocationRelativeTo(null);
        setVisible(Boolean.TRUE);
    }

    public void initVars() {
        numStr = BigDecimal.ZERO.toString();
        salve = "";
        num = new LinkedList<BigDecimal>();
        result = new BigDecimal("0", MathContext.DECIMAL32);
        operaciones.clear();;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel5 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        fieldNumeric = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btnSubtract = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btnMultiply = new javax.swing.JButton();
        btn0 = new javax.swing.JButton();
        btnPoint = new javax.swing.JButton();
        btnEqual = new javax.swing.JButton();
        btnDivision = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        btnClear = new javax.swing.JButton();
        btnSalve = new javax.swing.JButton();
        btnRecover = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(556, 386));
        setMinimumSize(new java.awt.Dimension(150, 100));
        setResizable(false);

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel5.setMinimumSize(new java.awt.Dimension(150, 100));

        jPanel2.setPreferredSize(new java.awt.Dimension(200, 30));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        fieldNumeric.setMargin(new java.awt.Insets(0, 0, 0, 0));
        fieldNumeric.setMinimumSize(new java.awt.Dimension(260, 30));
        fieldNumeric.setPreferredSize(new java.awt.Dimension(200, 30));
        jPanel2.add(fieldNumeric, new java.awt.GridBagConstraints());

        jPanel5.add(jPanel2);

        getContentPane().add(jPanel5, java.awt.BorderLayout.PAGE_START);

        jPanel3.setMaximumSize(new java.awt.Dimension(480, 160));
        jPanel3.setMinimumSize(new java.awt.Dimension(150, 100));
        jPanel3.setPreferredSize(new java.awt.Dimension(300, 160));
        java.awt.GridBagLayout jPanel3Layout = new java.awt.GridBagLayout();
        jPanel3Layout.columnWidths = new int[] {0, 5, 0};
        jPanel3Layout.rowHeights = new int[] {0};
        jPanel3Layout.columnWeights = new double[] {0.0};
        jPanel3Layout.rowWeights = new double[] {0.0};
        jPanel3.setLayout(jPanel3Layout);

        jPanel7.setLayout(new java.awt.GridLayout(4, 4, 15, 20));

        btn1.setText("1");
        btn1.setMinimumSize(new java.awt.Dimension(50, 23));
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });
        jPanel7.add(btn1);

        btn2.setText("2");
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });
        jPanel7.add(btn2);

        btn3.setText("3");
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });
        jPanel7.add(btn3);

        btnAdd.setText("+");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        jPanel7.add(btnAdd);

        btn4.setText("4");
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });
        jPanel7.add(btn4);

        btn5.setText("5");
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });
        jPanel7.add(btn5);

        btn6.setText("6");
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });
        jPanel7.add(btn6);

        btnSubtract.setText("-");
        btnSubtract.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubtractActionPerformed(evt);
            }
        });
        jPanel7.add(btnSubtract);

        btn7.setText("7");
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });
        jPanel7.add(btn7);

        btn8.setText("8");
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });
        jPanel7.add(btn8);

        btn9.setText("9");
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });
        jPanel7.add(btn9);

        btnMultiply.setText("*");
        btnMultiply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMultiplyActionPerformed(evt);
            }
        });
        jPanel7.add(btnMultiply);

        btn0.setText("0");
        btn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn0ActionPerformed(evt);
            }
        });
        jPanel7.add(btn0);

        btnPoint.setText(".");
        btnPoint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPointActionPerformed(evt);
            }
        });
        jPanel7.add(btnPoint);

        btnEqual.setText("=");
        btnEqual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEqualActionPerformed(evt);
            }
        });
        jPanel7.add(btnEqual);

        btnDivision.setText("/");
        btnDivision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDivisionActionPerformed(evt);
            }
        });
        jPanel7.add(btnDivision);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        jPanel3.add(jPanel7, gridBagConstraints);

        jPanel4.setLayout(new java.awt.GridLayout(3, 0, 0, 15));

        btnClear.setText("Limpiar");
        btnClear.setInheritsPopupMenu(true);
        btnClear.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnClear.setMaximumSize(new java.awt.Dimension(60, 100));
        btnClear.setMinimumSize(new java.awt.Dimension(50, 23));
        btnClear.setName(""); // NOI18N
        btnClear.setPreferredSize(new java.awt.Dimension(60, 40));
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        jPanel4.add(btnClear);

        btnSalve.setText("Guardar");
        btnSalve.setMaximumSize(new java.awt.Dimension(50, 23));
        btnSalve.setMinimumSize(new java.awt.Dimension(50, 23));
        btnSalve.setPreferredSize(new java.awt.Dimension(50, 23));
        btnSalve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalveActionPerformed(evt);
            }
        });
        jPanel4.add(btnSalve);

        btnRecover.setText("Recuperar");
        btnRecover.setMaximumSize(new java.awt.Dimension(50, 23));
        btnRecover.setMinimumSize(new java.awt.Dimension(50, 23));
        btnRecover.setPreferredSize(new java.awt.Dimension(50, 23));
        btnRecover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecoverActionPerformed(evt);
            }
        });
        jPanel4.add(btnRecover);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 14;
        jPanel3.add(jPanel4, gridBagConstraints);

        getContentPane().add(jPanel3, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        clearDisplay();
    }//GEN-LAST:event_btnClearActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        addActionNumber(this.btn1.getText());
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        addActionNumber(this.btn2.getText());
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        addActionNumber(this.btn3.getText());
    }//GEN-LAST:event_btn3ActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        addActionOperation(this.btnAdd.getText());
    }//GEN-LAST:event_btnAddActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        addActionNumber(this.btn4.getText());
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        addActionNumber(this.btn5.getText());
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        addActionNumber(this.btn6.getText());
    }//GEN-LAST:event_btn6ActionPerformed

    private void btnSubtractActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubtractActionPerformed
        addActionOperation(this.btnSubtract.getText());
    }//GEN-LAST:event_btnSubtractActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        addActionNumber(this.btn7.getText());
    }//GEN-LAST:event_btn7ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        addActionNumber(this.btn8.getText());
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
        addActionNumber(this.btn9.getText());
    }//GEN-LAST:event_btn9ActionPerformed

    private void btn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn0ActionPerformed
        addActionNumber(this.btn0.getText());
    }//GEN-LAST:event_btn0ActionPerformed

    private void btnPointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPointActionPerformed
        addActionNumber(this.btnPoint.getText());
    }//GEN-LAST:event_btnPointActionPerformed

    private void btnEqualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEqualActionPerformed
        addActionOperation(this.btnEqual.getText());
    }//GEN-LAST:event_btnEqualActionPerformed

    private void btnDivisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDivisionActionPerformed
        addActionOperation(this.btnDivision.getText());
    }//GEN-LAST:event_btnDivisionActionPerformed

    private void btnSalveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalveActionPerformed
        salve = this.fieldNumeric.getText();
    }//GEN-LAST:event_btnSalveActionPerformed

    private void btnRecoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecoverActionPerformed
        this.fieldNumeric.setText(salve);
    }//GEN-LAST:event_btnRecoverActionPerformed

    private void btnMultiplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMultiplyActionPerformed
        addActionOperation(this.btnMultiply.getText());
    }//GEN-LAST:event_btnMultiplyActionPerformed

    public void addActionNumber(String num) {
        String auxInput = String.format("%s%s", this.fieldNumeric.getText(), num);
        this.fieldNumeric.setText(auxInput);
    }

    public void addActionOperation(String oper) {
        String auxInput = this.fieldNumeric.getText();
        if (oper.equals("=")) {
            toExtract(auxInput);
            toDo();
            this.fieldNumeric.setText(result.toString());
        } else {
            String txtDisplay = String.format("%s%s", auxInput, oper);
            this.fieldNumeric.setText(txtDisplay);
        }
    }

    public void toExtract(String auxInput) {
        auxInput += "@";
        auxNum = "";
        operaciones.push(OPERATION.INIT);
        auxInput.chars().mapToObj(i -> (char) i).forEach(i -> {
            OPERATION operation = null;
            if (i == '+' || i == '-' || i == '*' || i == '/' || i == '=') {
                if (auxNum.isBlank() || OperationsUtils.isStringDecimalZero(auxNum)) {
                    num.add(BigDecimal.ZERO);
                } else {
                    num.add(new BigDecimal(auxNum, MathContext.DECIMAL32));
                }
                auxNum = "";
                operation = i == '+' ? OPERATION.ADD
                        : i == '-' ? OPERATION.SUBTRACT
                                : i == '*' ? OPERATION.MULITPY
                                        : i == '/' ? OPERATION.DIVISION : OPERATION.NONE;
                operaciones.push(operation);
            } else {
                if (i == '@') {
                    if (auxNum.isBlank() || OperationsUtils.isStringDecimalZero(auxNum)) {
                        num.add(BigDecimal.ZERO);
                    } else {
                        num.add(new BigDecimal(auxNum, MathContext.DECIMAL32));
                    }
                } else {
                    auxNum += i;
                }
            }
        });
    }

    public void toDo() {
        if (num.isEmpty()) {
            return;
        }
        for (OPERATION opr : operaciones) {
            BigDecimal element = num.poll();
            switch (opr.toString()) {
                case "INIT":
                    result = element;
                    break;
                case "ADD":
                    result = OperationsUtils.add(result, element);
                    break;
                case "SUBTRACT":
                    result = OperationsUtils.subtract(result, element);
                    break;
                case "MULITPY":
                    result = OperationsUtils.multiply(result, element);
                    break;
                case "DIVISION":
                    BigDecimal dividendo = element;
                    BigDecimal divisor = result;
                    if (BigDecimal.ZERO.equals(dividendo)) {
                        error();
                    } else {
                        result = OperationsUtils.division(divisor, dividendo);
                    }
                    break;
                default:
                    throw new AssertionError();
            };
        }
        operaciones.clear();

    }

    public void clearDisplay() {
        this.fieldNumeric.setText("");
    }

    public void error() {
        JOptionPane.showMessageDialog(null, "Operation no permit; Division by 0", "Error!", JOptionPane.ERROR_MESSAGE);
        initVars();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculadoraFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculadoraFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculadoraFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculadoraFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculadoraFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDivision;
    private javax.swing.JButton btnEqual;
    private javax.swing.JButton btnMultiply;
    private javax.swing.JButton btnPoint;
    private javax.swing.JButton btnRecover;
    private javax.swing.JButton btnSalve;
    private javax.swing.JButton btnSubtract;
    private javax.swing.JTextField fieldNumeric;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    // End of variables declaration//GEN-END:variables
}
